### ISSUE TITLE
Cambio de URL en el archivo GeojsonMapService.js

### ISSUE THREAD

**Issue by betCG** [geochicasosm/lascallesdelasmujeres#10]
Hola encontramos un error en el archivo GeojsonMapService.js, se debe cambiar la línea
`    this.urlData = 'https://raw.githubusercontent.com/labexp/lascallesdelasmujeres/develop';` 
por 
`    this.urlData = 'https://raw.githubusercontent.com/geochicas/lascallesdelasmujeres/master';`

**Comment by jessisena** [comment]
Hola,

Sí, estoy trabajando en un refactor ya lo había detectado. Gracias por avisar!
