### ISSUE TITLE
Propuesta para cambio de visualización de las ciudades en la página

### ISSUE THREAD

**Issue by tammypmc** [geochicasosm/lascallesdelasmujeres#4]
Geochicas, este Issue se realiza con el propósito de ofrecer mejoras en la manera que se presenta la interfaz de la página de Las Calles de las Mujeres, actualmente la página presenta la información de manera que se encuentra una lista con las ciudades disponibles en la parte izquierda de la pantalla ordenadas alfabéticamente sin ningún agrupamiento particular. Dado que el proyecto está creciendo cada vez más, países como Argentina presentan varias ciudades que han sido incluidas en el mapa de Las Calles de las Mujeres y en Costa Rica hay 3 ciudades próximas a ser añadidas al mismo, de esta manera se espera seguir recibiendo incrementalmente aportes que vayan ampliando la cantidad de ciudades por país en la página. 
Teniendo esto en mente, la propuesta presente se crea con la visión de crear una interfaz que agrupe las ciudades disponibles por el país al que pertenecen, de manera que se muestre la información más claramente y al mismo tiempo evitar confusiones dado que existen ciudades que tienen el mismo nombre en diferentes países (ej. San José).
La propuesta consiste en primeramente modificar el archivo constants.js donde se encuentra una lista de ciudades con su respectiva información. Se modificará la variable citiesList para convertirse en countriesList, y en esta lista se guardarán todas las ciudades existentes de un mismo país. 

- Actualmente el archivo tiene esta forma:
![citieslist](https://user-images.githubusercontent.com/17577503/45831438-9d13e380-bcbc-11e8-81f3-0fca877ee199.png)

- Esta sería la implementación de countriesList:
![countrieslist](https://user-images.githubusercontent.com/17577503/45831472-b7e65800-bcbc-11e8-80e7-d3992497dcc5.png)

Se utilizará countrieslist como una lista de objetos para almacenar un id, el nombre de cada país y  una lista de ciudades con la información que anteriormente se encontraba en citiesList. Además se modificará el código del index para adaptarlo al uso de la lista de países.

- Actualmente el panel se visualiza así:
![panel ciudades](https://user-images.githubusercontent.com/17577503/45831727-5b376d00-bcbd-11e8-9e55-6144d50dcca7.png)

- La propuesta es que se visualice de la siguiente manera:         
![panel paises](https://user-images.githubusercontent.com/17577503/45831788-7bffc280-bcbd-11e8-9a2d-80ef10fefe0a.png)

Los cambios propuestos en este Issue fueron originados en: labexp/lascallesdelasmujeres#2 y se encuentran ya implementados vía ese mismo fork del repositorio de Geochicas [labexp/lascallesdelasmujeres](https://github.com/labexp/lascallesdelasmujeres/tree/develop) 
Este incentivo se hace con la meta de adaptar la página de Las Calles de las Mujeres al rápido crecimiento y progreso que se espera, así manteniendo la legibilidad de la página sin importar la cantidad de datos que se añadan.

**Comment by jessisena** [comment]
Hola Tammy,
Mil gracias por el aporte. Os comento varias cosas:

- He revisado la nueva estructura de la lista organizada por países, y está perfecta, así que en principio no habría problema en aceptarla.

- Necesitaría revisar también el nuevo código de index.js y index.html. En el repositorio donde tenéis el fork no lo he encontrado, así que imagino que no lo tenéis subido aún.

- Queda pendiente una llamada colectiva para validar la visualización del panel que habéis propuesto.

- Por último, y lo más importante, cómo habéis planteado la visualización del panel en modo pantalla móvil? Es el único tema que nosotras teníamos pendiente, y por el cuál aún no se había hecho la implementación de esta mejora.

Un abrazo,
